sudo: required

language: php

dist: trusty

php:
   - 7.2
   - 7.3
   - 7.4

before_script:
  composer install
script: composer test

after_script:
  echo "no tests erros"

after_failure: echo "errors in tests"